version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        environment:
            - PORT=3000
            - DB_HOST=db
            - DB_USER=root
            - DB_PASSWORD=my-secret-pw
            - DB_NAME=items_db
        depends_on:
            - db

    db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: my-secret-pw
            MYSQL_DATABASE: items_db
        ports:
            - "3306:3306"
        volumes:
            - ./mysql_data:/var/lib/mysql # Project-specific volume for MySQL data
            - ./migrations:/docker-entrypoint-initdb.d

volumes:
    db_data:
